-- cubo original mge
SELECT 
SUM(DRE.QTPROD) As "R2_QTDE",
SUM(DRE.QTDDEV) As "R2_QTDDEV",
SUM(DRE.QTPROD-DRE.QTDDEV) As "R2_QTDLIQ",
SUM(DRE.VLMED*DRE.QTPROD-DRE.QTDDEV*DRE.VLMED) As "R2_VALOR",
DRE.DESCRPROD||'('||DRE.CODPROD||')' As "R2_PRODUTO",
CUS1.AD_CLACUS2 As "R2_CLACUS2",
DRE.UFPARC As "R2_UFEMP",
CUS1.AD_CLACUS As "r2_clacus",
PAR.RAZAOSOCIAL As "R2_RAZAO SOCIAL PARCEIRO",
CIDP.NOMECID As "R2_CIDADE PARCEIRO",
CUS1.DESCRCENCUS As "R2_CCUSTO",
DRE.UNNEG As "R2_UNNEG",
SUM(DRE.RECLIQ*(DRE.QTPROD-DRE.QTDDEV)) As "R2_RECLIQ",
SUM(DRE.CUSSEMICM*(DRE.QTPROD-DRE.QTDDEV)) As "R2_CUSTO",
SUM((DRE.FRETE+DRE.FRETE_MARITIMO)*(DRE.QTPROD-DRE.QTDDEV)+CASE WHEN DRE.VLMED=0 THEN 0 ELSE DRE.COMISS*(DRE.QTPROD-DRE.QTDDEV)+NVL(DRE.CROSS,0)*(DRE.QTPROD-DRE.QTDDEV) END) As "R2_DESPCOML",
SUM(DRE.VLROUTROS*(DRE.QTPROD-DRE.QTDDEV)) As "R2_VLROUTROS",
SUM(CASE WHEN UNNEG='MTZ' THEN OA1 WHEN UNNEG='GYN' THEN OA2 WHEN UNNEG='BSB' THEN OA3 WHEN UNNEG='ANP' THEN OA4 WHEN UNNEG='UDI' THEN OA5 WHEN UNNEG='PA' THEN OA6 WHEN UNNEG='GRE' THEN OA7 WHEN UNNEG='ENT' THEN OA9 ELSE OA8 END*(DRE.QTPROD-DRE.QTDDEV)) As "R2_OA",
-NVL((select PAR11.NUMDEC from tsipar par11 where  PAR11.CHAVE='SF_' || TO_CHAR(:DAT1 ,'YYYYMM') || '_OP'  AND PAR11.CODUSU=0),0) /NVL((select PAR11.NUMDEC from tsipar par11 where  PAR11.CHAVE='SF_' || TO_CHAR(:DAT1 ,'YYYYMM') || '_KG'  AND PAR11.CODUSU=0),01) As "R2_OP",
-NVL((select PAR11.NUMDEC from tsipar par11 where  PAR11.CHAVE='SF_' || TO_CHAR(:DAT1 ,'YYYYMM') || '_OAADM'  AND PAR11.CODUSU=0),0) /NVL((select PAR11.NUMDEC from tsipar par11 where  PAR11.CHAVE='SF_' || TO_CHAR(:DAT1 ,'YYYYMM') || '_KG'  AND PAR11.CODUSU=0),00) As "R2_OAADM",
DRE.CODPROD As "R2_CODPROD",
GER.APELIDO As "R2_GERENTE",
VEN.APELIDO As "R2_VENDEDOR",
PRO.AD_FAMILIA As "Familia produto acabado",
TPP.DESCRTIPPARC As "Perfil Principal",
DRE.CODEMP As "R2_CODEMP",
PAR.CODPARC As "R2_CODPARC",
REG.NOMEREG As "R2_REGIAO",
GRU.CODGRUPOPROD||'-'||GRU.DESCRGRUPOPROD As "R2_DESCRGRUPO",
SUM(DRE.VLDESC*(DRE.QTPROD-DRE.QTDDEV)) As "R2_VLDESC",
SUM((DRE.FRETE+DRE.FRETE_MARITIMO)*(DRE.QTPROD-DRE.QTDDEV)) As "R2_FRETE",
SUM(DRE.VLRICMSCID*(DRE.QTPROD-DRE.QTDDEV)) As "R2_VLRICMSCID",
SUM(DRE.ICMS_REC*(DRE.QTPROD-DRE.QTDDEV)) As "R2_ICMS_REC",
SUM(DRE.PROTEGE*(DRE.QTPROD-DRE.QTDDEV)) As "R2_PROTEGE",
SUM(DRE.CREDOUT*(DRE.QTPROD-DRE.QTDDEV)) As "R2_CREDOUT",
SUM(DRE.PISCID*(DRE.QTPROD-DRE.QTDDEV)) As "R2_PISCID",
SUM(DRE.PIS_COFINS_REC*(DRE.QTPROD-DRE.QTDDEV)) As "R2_PIS_COFINS_REC",
SUM(DRE.COFINS*(DRE.QTPROD-DRE.QTDDEV)) As "R2_COFINS",
SUM(DRE.CRED_PIS_COFINS) As "R2_CRED_PIS_COFINS",
SUM(DRE.ST*(DRE.QTPROD-DRE.QTDDEV)) As "R2_ST",
SUM(DRE.COMISS*(DRE.QTPROD-DRE.QTDDEV))  As "R2_COMISS",
(SELECT SUM(DESP_DIR_POND) FROM DRE_DESP_DIR_POND WHERE REFERENCIA = :DAT1)*SUM(DRE.QTPROD-DRE.QTDDEV) As "R2_DESPDIR",
(SELECT SUM(DESPFIN) FROM DRE_DESP_DIR_POND WHERE REFERENCIA = :DAT1) * SUM(DRE.QTPROD-DRE.QTDDEV) As "R2_DESPFIN",
FC_DIVIDE(SUM(CROSS*CROSSQT),SUM(CROSSQT)) As "R2_CROSS",
(SELECT V.CODVEND FROM TGFVEN V ,TGFPAR P WHERE P.AD_CODPROMVDA = V.CODVEND AND P.CODPARC = PAR.CODPARC) As "R2_CODPROMOTOR",
(SELECT V.APELIDO FROM TGFVEN V ,TGFPAR P WHERE P.AD_CODPROMVDA = V.CODVEND AND P.CODPARC = PAR.CODPARC) As "R2_PROMOTOR",
(SELECT V.AD_REGSAGA FROM TGFVEN V ,TGFPAR P WHERE P.AD_CODPROMVDA = V.CODVEND AND P.CODPARC = PAR.CODPARC) As "R2_SUPERVISOR_PROMOTOR" 
 FROM DRE
, TSICUS CUS1
, TGFPAR PAR
, TSICID CIDP
, TGFVEN VEN
, TGFVEN GER
, TGFPRO PRO
, TGFTPP TPP
, TSIREG REG
, TGFGRU GRU
WHERE DRE.CODCENCUS = CUS1.CODCENCUS
AND DRE.CODPARC = PAR.CODPARC
AND PAR.CODCID = CIDP.CODCID
AND DRE.CODVEND = VEN.CODVEND
AND GER.CODVEND = VEN.CODGER
AND PAR.CODTIPPARC = TPP.CODTIPPARC
AND REG.CODREG =  NVL(VEN.AD_REGVENDA,0)
AND DRE.CODPROD=PRO.CODPROD
AND PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
 AND (( DRE.GRUPO in ('Venda','Dev. Venda'))   AND 
 ( DRE.DTFATUR >= :DAT1)   AND 
 ( DRE.DTFATUR <= :DAT2)   AND 
 (( PRO.CODGRUPOPROD >= 01000000 )    AND 
 ( PRO.CODGRUPOPROD <= 01999999) OR
 PRO.CODGRUPOPROD IN (1040600, 3020200,3020300,3010100,3030100,3030200,3030100,3030200,1040500,3020400,3020500,3020600) OR
 DRE.CODPROD IN (1592,3758,16865,18503))  AND 
 DRE.CODTIPOPER not in (130,142,1300,1313)
 )
/ INICIO CERTIFICACAO TSICUS=CUS1, TGFPAR=PAR, TGFPRO=PRO, TGFGRU=GRU, /
/ FIM CERTIFICACAO /
Group by DRE.DESCRPROD||'('||DRE.CODPROD||')'
, CUS1.AD_CLACUS2
, DRE.UFPARC
, CUS1.AD_CLACUS
, PAR.RAZAOSOCIAL
, CIDP.NOMECID
, CUS1.DESCRCENCUS
, DRE.UNNEG
, DRE.CODPROD
, GER.APELIDO
, VEN.APELIDO
, PRO.AD_FAMILIA
, TPP.DESCRTIPPARC
, DRE.CODEMP
, PAR.CODPARC
, REG.NOMEREG
, GRU.CODGRUPOPROD||'-'||GRU.DESCRGRUPOPROD
