prompt Importing table ad_tsfdre...
set feedback off
set define off
insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (300000, 1, 'N', -999999999, 'Despesas Comerciais', null, null, null);

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (400000, 1, 'S', -999999999, 'Resultado Líquido antes Desp. Acessórias', null, null, null);

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (500000, 1, 'N', -999999999, 'Despesas Acessórias', null, null, null);

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (600000, 1, 'S', -999999999, 'Resultado Líquido após Desp. Acessórias', null, null, null);

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (700000, 1, 'N', -999999999, 'Despesas/Receitas Financeiras', null, null, null);

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (800000, 1, 'N', -999999999, 'Despesas com Diretoria', null, null, null);

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (102001, 3, 'S', 102000, 'ICMS sobre Venda', 'VLRICMSORIG', 'VLRICMS + (VLRTRX * AD_PKG_DRE.GETVALORMETA(NUNOTA,SEQUENCIA,102001))', 'FC_DIVIDE(SUM(VLRICMSORIG),SUM(QTDNEG))');

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (101000, 2, 'S', 100000, '(A)Preço de Venda', 'VLRMED', '((VLRTOT+VLRIPI+VLRSUBST+VLRDESC+VLRREPRED)-(FC_DIVIDE(VLRDESCTOT,NVL(PESO,0))*QTDNEG))/ QTDNEG', 'FC_DIVIDE(SUM(VLRMED * QTDNEG) , SUM (QTDNEG))');

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (102000, 2, 'N', 100000, 'Icms sobre Venda a Rec.', null, null, null);

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (102002, 3, 'S', 102000, 'Crédito Outorgado sobre Venda', 'CREDOUTVDA', 'VLRUNIT * AD_PKG_DRE.GETVALORMETA(NUNOTA, SEQUENCIA,0102002)', 'FC_DIVIDE(SUM(CREDOUTVDA), SUM(QTDNEG))');

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (102003, 3, 'S', 102000, 'Crédito Outorgado sobre Transf.', 'CREDOUTTRX', 'VLRTRX * AD_PKG_DRE.GETVALORMETA(NUNOTA, SEQUENCIA,0102003)', 'FC_DIVIDE(SUM(CREDOUTTRX) ,SUM(QTDNEG))');

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (102004, 3, 'S', 102000, 'Crédito Presumido', 'ICMSPRESUM', 'VLRUNIT * AD_PKG_DRE.GETVALORMETA(NUNOTA,SEQUENCIA,0102004)', 'FC_DIVIDE(SUM(ICMSPRESUM),SUM(QTDNEG))');

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (103000, 2, 'N', 100000, 'PIS/COFINS', null, null, null);

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (103001, 3, 'S', 103000, 'PIS', 'PISORIG', 'VLR_IMP(NUNOTA, SEQUENCIA, ''PIS'', ''D'')', 'FC_DIVIDE(SUM(PISORIG),SUM(QTDNEG))');

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (103002, 3, 'S', 103000, 'COFINS', 'COFINS', 'VLR_IMP(NUNOTA, SEQUENCIA, ''COFINS'', ''D'')', 'FC_DIVIDE(SUM(COFINS),SUM(QTDNEG))');

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (103003, 3, 'S', 103000, 'Crédito PIS/COFINS', 'CREDPISCOFINS', 'CASE WHEN CODGRUPOPROD = 1040200 THEN 
CREDMP2
ELSE
FC_DIVIDE((VLR_IMP(NUNOTA, SEQUENCIA, ''PIS'', ''C'') + VLR_IMP(NUNOTA, SEQUENCIA, ''COFINS'', ''C'')),(FC_DIVIDE((VLRTOT + VLRIPI + VLRSUBST - VLRDESC), (QTDNEG))) * 100)
END', 'FC_DIVIDE(SUM(CREDPISCOFINS),(SUM(QTDNEG)*100))');

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (104000, 2, 'S', 100000, 'Receita Líquida (A-B-C)', 'RECLIQUIDA', null, '(FC_DIVIDE(SUM(VLRMED),SUM(QTDNEG))) - (FC_DIVIDE(SUM(VLRICMSORIG) -  SUM(CREDOUTVDA + CREDOUTRX + ICMSPRESUM),SUM(QTDNEG))) - (FC_DIVIDE(SUM(PISORIG) + SUM(COFINS) + SUM(CREDPISCOFINS),SUM(QTDNEG)))');

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (201000, 2, 'S', 200000, 'Custos', 'CUSGER', 'NVL(OBTEMCUSTO(CODPROD,''S'',1,''S'',1100,''N'','' '',DTFATUR,1),0)', 'CUSGER');

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (202000, 2, 'S', 200000, 'OverHead', null, null, null);

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (203000, 2, 'S', 200000, 'CrossDock', null, null, null);

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (102005, 3, 'S', 102000, '(B) Icms Sobre Venda Rec.', null, null, 'FC_DIVIDE(SUM(VLRICMSORIG) -  SUM(CREDOUTVDA + CREDOUTRX + ICMSPRESUM),SUM(QTDNEG))');

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (103004, 3, 'S', 103000, '(C)PIS+COFINS++CRDPIS/COFINS', null, null, 'FC_DIVIDE(SUM(PISORIG) + SUM(COFINS) + SUM(CREDPISCOFINS),SUM(QTDNEG))');

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (301000, 2, 'S', 300000, 'Fretes', 'FRETE', null, 'FC_DIVIDE(SUM(FRETE)*SUM(QTDNEG),SUM(QTDNEG))');

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (302000, 2, 'S', 300000, 'Comissões', 'VLRCOMISSAO', '(((((VLRUNIT + VLRIPI - VLRDESC) * QTDNEG * 1.5) / 100) * CASE WHEN CODEMP = 1 AND UF = ''PA'' AND CODUNE IN (8,9) /*EXT, GRE*/ THEN 0 ELSE 1 END)/QTDNEG)', 'FC_DIVIDE(SUM(VLRCOMISSAO)*SUM(QT DNEG),SUM(QTDNEG))');

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (303000, 2, 'S', 300000, 'Total Desp. Comerciais', null, null, 'FC_DIVIDE((SUM(FRETE) - SUM(VLRCOMISSAO))*SUM(QTDNEG),SUM(QTDNEG))');

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (501000, 2, 'N', 500000, 'PROTEGE GOIÁS', null, null, null);

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (502000, 2, 'S', 500000, 'Proteção Educ.Trib (DF)', null, 'ROUND(CASE WHEN SUBSTR(P_UFPARC, 1, 2) = ''DF'' THEN P_VLMED * 0.05 / 100 ELSE 0 END, 3);', null);

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (503000, 2, 'S', 500000, 'Fundo Geração de Emprego (DF)', null, 'P_FUNDOGER := 0;', null);

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (504000, 2, 'S', 500000, 'Substituição Tributária', null, null, null);

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (505000, 2, 'S', 500000, 'Total Desp. Acessórias', null, null, null);

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (701000, 2, 'S', 700000, 'Despesas Financeiras', null, null, null);

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (702000, 2, 'S', 700000, 'Receitas Financeiras', null, null, null);

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (703000, 2, 'S', 700000, 'Descontos Concedidos', null, null, null);

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (704000, 2, 'S', 700000, 'Total Despesas/Receitas Financeiras', null, null, null);

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (801000, 2, 'S', 800000, 'Despesas com Diretoria', null, null, null);

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (802000, 2, 'S', 800000, 'Outras Despesas', null, null, null);

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (803000, 2, 'S', 800000, 'Total de Despesas com Diretoria', null, null, null);

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (900000, 1, 'S', -999999999, 'Resultado Líquido Geral', null, null, null);

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (1000000, 1, 'S', -999999999, 'Margem de Contribuição(%)', null, null, null);

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (100000, 1, 'N', -999999999, 'Receitas', null, null, null);

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (200000, 1, 'N', -999999999, 'Custos', null, null, null);

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (501001, 3, 'S', 501000, 'Protege Goiás Venda', null, 'P_PROTEGE := ROUND(CASE WHEN SUBSTR(P_UFPARC, 1, 2) IN (''EX'') THEN 0 WHEN P_CODGRUPOPROD IN (1040200, 1040400, 1090100,3010100,3020300) THEN 
CASE WHEN P_UFPARC IN (''PA-7'', ''DF-5'', ''MG-14'') THEN P_VLRTRX ELSE P_VLMED END * 0.02 * 0.15
ELSE 
CASE WHEN P_UFPARC IN (''PA-7'', ''DF-5'', ''MG-14'') THEN P_VLRTRX ELSE P_VLMED END * 0.09 * 0.15 END, 3);
		
', null);

insert into ad_tsfdre (CODMETA, GRAU, ANALITICO, CODMETAPAI, DESCRMETA, NOMECAMPO, FORMULA, FORMREL)
values (501002, 3, 'S', 501000, 'Protege Goiás Transf.', null, null, null);

prompt Done.
