CREATE OR REPLACE VIEW AD_TSFROCR AS
--SELECT '' AS ANALITICO,0 AS CODTIPPARC,0 AS CODTIPPARCPAI,'' AS DESCRPERFIL,0 AS GRAU FROM DUAL;
 Select 
 T.CODTIPPARC,
 T.DESCRTIPPARC DESCRPERFIL,
 T.CODTIPPARCPAI,
 T.GRAU,
 T.ANALITICO
 From 
 tgftpp t
 Where t.codtipparc >= 99000000
 Order By t.codtipparc;
